import type { AgentColorName } from '../../../tools/AgentTool/agentColorManager.js'
import type { AgentMemoryScope } from '../../../tools/AgentTool/agentMemory.js'
import type { CustomAgentDefinition } from '../../../tools/AgentTool/loadAgentsDir.js'
import type { SettingSource } from '../../../utils/settings/constants.js'

/**
 * Mutable state passed between steps in the "Create Agent" wizard.
 * Fields are progressively populated as the user moves through the flow.
 * `finalAgent` is assembled by the Color step before confirmation.
 */

export type AgentWizardData = {
  systemPrompt?: string // Final system prompt
  agentType?: string // Agent type slug (directory name)
  generationPrompt?: string // Full user instructions entered in "Generate" mode
  selectedTools?: string[] // Restrict available tools; undefined means all tools
  whenToUse?: string // "When to use" description
  location?: SettingSource // Save location: project or personal settings
  selectedModel?: string // Override default model (optional)
  selectedColor?: AgentColorName // Terminal highlight color (optional)
  wasGenerated?: boolean // Whether the configuration was auto-generated by a model
  method?: 'generate' | 'manual' // Creation path: generate vs manual
  isGenerating?: boolean // Generation request in progress (used for UI debouncing)

  generatedAgent?: {
    identifier: string // Suggested agentType returned by the generator
    whenToUse: string // Description returned by the generator
    systemPrompt: string // System prompt returned by the generator
  }

  selectedMemory?: AgentMemoryScope // Memory scope selected in the Memory step

  finalAgent?: CustomAgentDefinition // Complete agent definition draft before saving
}